* bibrest
- Simple RESTful API to expose bibtex library
- Based on Python, using =flask= and =pybtex=
- Intended to be used as backend for websites rendering bibtex reference lists 

** Installation
Install flask and pybtex

#+begin_src bash
sudo pip install flask pybtex
#+end_src

Then, the development flask server can be started with

#+begin_src bash
python bibrest.py
#+end_src

It will serve the test.bib in the same folder. 

** Resources
*** =/bibs?author=<authorlist>&project=<projectlist>&reverse=True&start=123=
Will return all bibtex entries, including the project field. All arguments are optional

Arguments:
- =reverse=: set to =True= if order should be anti-chronologic
- =author=: give one or more author names (comma separated). Will return bibtex of all entries with those strings in author field.
- =project=: give one or more project names (comma separated). Will return bibtex of all entries with those projects.
- =start=: give starting year from which on results are returned
Example use:
=foo.bar/bibs?author=tippenhauer,mathur&project=aspire&reverse=True&start=2014=
*** =/bib/<key>=
Will return bibtex for article =<key>=

*** =/projects=
Will return human readable list of all project keys in the database

*** =/authors=
Will return human readable list of all authors in the database
** Deployment
For more stable deployments, we recommend gunicorn, apache, or nginx.

** Todo/known bugs
- Only one project per entry
- Add ?year=2016 filter
** Author
Nils Ole Tippenhauer, SUTD, 2016
